"""Add created_by to procedures table

Revision ID: 19477453b1ce
Revises: 1e2b6910987d
Create Date: 2026-02-04 14:41:53.341446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19477453b1ce'
down_revision = '1e2b6910987d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###