"""Add rooms and beds tables

Revision ID: 46c69536e919
Revises: 9d9a18108860
Create Date: 2026-01-30 10:41:29.559846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c69536e919'
down_revision = '9d9a18108860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###