"""Remove useless statuses

Revision ID: 6b7a78f871f0
Revises: 19477453b1ce
Create Date: 2026-02-09 11:52:20.416349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7a78f871f0'
down_revision = '19477453b1ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###