"""Update MedicalRecord model

Revision ID: 7c1fe5151750
Revises: 56dbd7119f65
Create Date: 2026-02-02 13:34:34.957684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1fe5151750'
down_revision = '56dbd7119f65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###