"""Add created_by to procedures table

Revision ID: 7ca8f5397fe1
Revises: 7c1fe5151750
Create Date: 2026-02-02 13:43:48.036438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca8f5397fe1'
down_revision = '7c1fe5151750'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'procedures', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_column('procedures', 'created_by')
    # ### end Alembic commands ###