"""Add rooms and beds tables

Revision ID: 9d9a18108860
Revises: 75346d6baa10
Create Date: 2026-01-30 10:36:25.199966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9a18108860'
down_revision = '75346d6baa10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('document_id', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('branch_id', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('department_id', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('department_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'department_name')
    op.drop_column('patients', 'department_id')
    op.drop_column('patients', 'branch_id')
    op.drop_column('patients', 'document_id')
    # ### end Alembic commands ###